name: Deploy To Dev Env

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/cd.yml
    with:
      environment: dev
      envVariableFilePath: ./.github/variables/dev.deployment.env
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_REGISTRY_PACKAGES: ${{ secrets.GH_REGISTRY_PACKAGES }}
      PA_TOKEN: ${{ secrets.PA_TOKEN }}